const { Router } = require('express')
const controller = require('../controllers/tournament.controller')
const upload = require('../middlewares/upload')
const auth = require('../middlewares/auth')

module.exports = Router()
    .get('/', controller.get_all)
    .get('/games', controller.get_game)
    .get('/game/:id', controller.get_game)
    .put('/game/win/:id/:user', controller.win_game)
    .get('/games/time', auth, controller.get_time_line)
    .post('/', upload.single('file'), controller.create)
    .put('/start/:id', controller.start)
    .put('/attend/:id', auth, controller.attend)
    // .delete('/:id')